Repository mamori-i-japan/mamori-i-japan-api, pull requests merged in 2020-06, with the labels that each got.

#171 🐛 Add an index to diagnosisKeys collection
  firebase.firestore.indexes.json
Labels: bug

#172 🆙 Update CHANGELOG.md for v0.1.1
  CHANGELOG.md
Labels: enhancement

#173 📚 Add external links to readme
  README.md
Labels: documentation
