Repository mamori-i-japan/mamori-i-japan-api, pull requests merged in 2020-05, with the labels that each got.

#158 📛 Change the descriptions
  README.md
  package.json
Labels: enhancement

#150 ♻️ Tiny refactorings for configuration files
  .node-version
  .prettierignore
  .prettierrc
  .vscode/extensions.json
  .vscode/settings.json
  .vscode/tasks.json
  src/users/users.repository.ts
Labels: enhancement

#155 🆙 Update version 0.0.1 to 0.1.0
  package.json
Labels: enhancement

#160 📝 Add badges to README
  README.md
Labels: documentation

#164 📝 Fix the CircleCI link to a public one
  README.md
Labels: enhancement

#161 🎉 Add demo environment instead of prd
  .circleci/config.yml
  .firebaserc
  README.md
  package.json
  serverless.yml
  src/lambda-swagger.ts
  src/main.ts
Labels: enhancement

#159 🥥 Add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation

#162 📛 Rename まもりあいJAPAN to まもりあいJapan
  LICENSE
  README.md
  package.json
Labels: bug

#163 🆙 Add CHANGELOG.md
  CHANGELOG.md
Labels: enhancement

#165 📚 Update ACL flow example
  docs/ACL.svg
  docs/acl.pu
Labels: documentation

#168 [feature]add cors setting for local environment
  src/main.ts
Labels: bug

#167 [fix]`package-lock.json` version is old
  package-lock.json
Labels: bug

#166 📚 Add env info to README
  README.md
Labels: documentation

#169 📚 Update README doc
  README.md
Labels: documentation
